### ISSUE TITLE
More than 2-dimensional data structure is not supported without a batch dimension

### ISSUE THREAD

**Issue by Sud11111** [farhadnkm/Fringe.Py#1]
I ran the example given on https://pypi.org/project/fringe/ and I am getting the following error:-
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-5-691d5f4eaa84>](https://localhost:8080/#) in <module>()
      2 from fringe.solvers.AngularSpectrum import AngularSpectrumSolver as AsSolver
      3 
----> 4 solver = AsSolver(shape=obj.shape, dr=1, is_batched=False, padding="same", pad_fill_value=0, backend="Numpy")
      5 rec = solver.solve(hologram, k=2*pi/500e-3, z=-1000)
      6 amp, phase = abs(rec), angle(rec)

[/usr/local/lib/python3.7/dist-packages/fringe/solvers/AngularSpectrum.py](https://localhost:8080/#) in __init__(self, shape, dr, is_batched, padding, pad_fill_value, backend)
     46 
     47         if len(shape) > 2 and not is_batched:
---> 48             raise ValueError("More than 2-dimensional data structure is not supported without a batch dimension.")
     49         elif len(shape) > 3:
     50             raise ValueError("More than 3-dimensional data structure is not supported.")

ValueError: More than 2-dimensional data structure is not supported without a batch dimension.

**Comment by farhadnkm** [comment]
Looks like there was a little bug in IO pipeline which was missed in the last update. Fixed the issue now. Package is upgraded to 1.0.4. Missing addresses are also updated in the example files.
