### ISSUE TITLE
The units in AngularSpectrumSolver

### ISSUE THREAD

**Issue by HakuRemu** [farhadnkm/Fringe.Py#2]
Dear Farhadnkm,

What are the units used in AngularSpectrumSolver? I see you have used the wavenumber 

>k=2 * np.pi/500e-3 

the pixel size

> dr=1

and the axial coordinate 

> z=-1000

in the example [https://github.com/farhadnkm/Fringe.Py/blob/master/examples/diffraction.ipynb](url). I think the units would be μm,  am I right?
Thank you for your support!

**Comment by farhadnkm** [comment]
That's correct.
But you can use any value/unit for these parameters.
